-- 用户表
CREATE TABLE `sysuser` (
  `user_id` mediumint(9) NOT NULL,
  `user_name` varchar(20) DEFAULT NULL COMMENT '用户名',
  `nike_name` varchar(10) DEFAULT NULL COMMENT '昵称',
  `passwd` char(32) DEFAULT NULL COMMENT '密码',
  `user_type` char(1) DEFAULT '4' COMMENT '3：管理员 4：子账号 ',
  `role_id` int(11) DEFAULT NULL COMMENT '角色id',
  `org_id` varchar(100) DEFAULT NULL COMMENT '机构id',
  `real_name` varchar(10) DEFAULT NULL COMMENT '真实姓名',
  `email` varchar(50) DEFAULT NULL COMMENT '邮箱',
  `loginnum` int(11) DEFAULT '0' COMMENT '登录次数',
  `logintime` datetime DEFAULT NULL COMMENT '最后一次登录时间',
  `loginip` varchar(20) DEFAULT NULL COMMENT '登录ip',
  `state` char(1) DEFAULT NULL COMMENT '0：启用 1：禁用',
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统用户表';


-- 商品表
CREATE TABLE `goods` (
  `goods_id` mediumint(9) NOT NULL COMMENT '商品标识',
  `cust_id` mediumint(9) NOT NULL COMMENT '会员标识',
  `cat_attr` varchar(200) NOT NULL COMMENT '所属分类',
  `goods_name` varchar(100) NOT NULL COMMENT '商品名称',
  `goods_no` varchar(20) NOT NULL COMMENT '商品编号',
  `goods_wd` varchar(100) DEFAULT NULL COMMENT '商品关键字',
  `brand_id` mediumint(9) DEFAULT NULL COMMENT '商品品牌',
  `list_img` varchar(100) DEFAULT NULL COMMENT '商品列表图片',
  `img_path` varchar(600) DEFAULT NULL COMMENT '商品图片',
  `goods_video` varchar(200) DEFAULT NULL COMMENT '商品视频',
  `goods_detail` text COMMENT '商品详细描述',
  `self_cat` mediumint(9) DEFAULT NULL COMMENT '商品自定义分类',
  `up_date` datetime NOT NULL COMMENT '上架时间',
  `down_date` datetime NOT NULL COMMENT '下架时间',
  `weight` float DEFAULT NULL COMMENT '重量',
  `unit` varchar(10) DEFAULT NULL COMMENT '计量单位',
  `is_ship` char(1) NOT NULL DEFAULT '' COMMENT '0：免运费，1：半自动，2：运费模板 ',
  `seo_titel` varchar(100) DEFAULT NULL COMMENT 'SEO商品标题',
  `seo_keyword` varchar(50) DEFAULT NULL COMMENT 'SEO商品关键字',
  `seo_desc` varchar(200) DEFAULT NULL COMMENT 'SEO商品描述',
  `relate_goods` varchar(300) DEFAULT NULL COMMENT '相关商品ID串',
  `give` varchar(100) DEFAULT NULL COMMENT '商家备注',
  `lab` char(1) NOT NULL COMMENT '见参数配置表    0：热卖 1：精品 2：新品 3： 橱窗推荐  4:热销',
  `busi_remark` varchar(300) DEFAULT NULL COMMENT '商品标签',
  `is_up` char(1) DEFAULT NULL COMMENT '是否下架 0:是 1:否',
  `is_del` char(1) NOT NULL COMMENT '是否删除 0:是 1:否',
  `info_state` char(1) NOT NULL COMMENT '审核状态 0：未审核 1：审核通过 2：审核不通过 3：禁用',
  `no_reason` varchar(100) DEFAULT NULL COMMENT '未通过理由',
  `ship_id` int(11) DEFAULT NULL COMMENT '运费模板',
  `in_date` datetime NOT NULL COMMENT '发布时间',
  `user_name` varchar(20) NOT NULL COMMENT '操作人',
  `click_num` int(11) DEFAULT NULL COMMENT '点击量',
  `volume` varchar(10) DEFAULT NULL COMMENT '物流体积',
  `logsweight` varchar(10) DEFAULT NULL COMMENT '物流重量',
  `is_virtual` char(1) NOT NULL COMMENT ' 商品是否虚拟 0:是  1：否 ',
  `sort_order` int(11) DEFAULT NULL COMMENT '排序',
  PRIMARY KEY (`goods_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='记录商品信息';


-- 订单表
CREATE TABLE `goodsorder` (
  `order_id` char(17) NOT NULL COMMENT 'order_id',
  `buy_cust_id` mediumint(9) NOT NULL COMMENT '买家会员标识',
  `sell_cust_id` mediumint(9) NOT NULL COMMENT '卖家会员标识',
  `consignee` varchar(20) NOT NULL COMMENT '收货人姓名',
  `area_attr` varchar(100) NOT NULL COMMENT '所在地区串',
  `buy_address` varchar(200) DEFAULT NULL COMMENT '详细地址',
  `zip_code` int(11) DEFAULT NULL COMMENT '邮编',
  `telephone` varchar(20) DEFAULT NULL COMMENT '电话',
  `mobile` int(11) DEFAULT NULL COMMENT '手机',
  `goods_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品总金额',
  `comm_free` decimal(10,2) DEFAULT NULL COMMENT '手续费费用',
  `ship_free` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '配送费用',
  `insured` decimal(10,2) DEFAULT NULL COMMENT '保价费用',
  `why_price` decimal(10,2) DEFAULT NULL COMMENT '是否涨价',
  `tatal_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
  `pay_id` int(11) NOT NULL COMMENT '付款方式标识',
  `send_mode` int(11) NOT NULL COMMENT '配送方式标识',
  `order_state` char(1) NOT NULL COMMENT '订单状态',
  `order_time` datetime NOT NULL COMMENT '下单时间',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `send_time` datetime DEFAULT NULL COMMENT '发货时间',
  `sure_time` datetime DEFAULT NULL COMMENT '确认时间',
  `mem_remark` varchar(300) DEFAULT NULL COMMENT '会员留言',
  `send_num` varchar(30) DEFAULT NULL COMMENT '物流编号',
  `is_virtual` char(1) DEFAULT NULL COMMENT '是否虚拟 0是1否',
  `order_type` char(1) DEFAULT NULL COMMENT '订单类型',
  `mark_id` varchar(12) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品订单信息';
