server:
  port: 8080
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 100
        min-idle: 5
        max-idle: 20
#    timeout: 1000
